### ISSUE TITLE
CLOSED: Does not work with font-awesome JS

### ISSUE THREAD

**Issue by petervanderwalt** [furcan/IconPicker#3]
If I use 

    <link rel="stylesheet" href="/lib/furcanIconPicker/dist/fontawesome-5.11.2/css/all.min.css">

it works (but I can't use CSS-only of font-awesome, we depend on some of the JS functionality

![withoutjs](https://user-images.githubusercontent.com/31449271/79583425-63d86b00-80cd-11ea-8be3-aac0648b1b70.png)

Font Awesome with JS says "**When using our SVG framework, remember that Font Awesome-based ```<i>``` DOM elements are replaced with new ```<svg>``` elements by default. Be sure that your css rules target the right elements.**"

So when using it with JS instead 

  <script type="text/javascript" src="lib/fontawesome5/js/all.min.js"></script>

It fails (can't click icons, etc)

![withjs](https://user-images.githubusercontent.com/31449271/79583445-689d1f00-80cd-11ea-97cd-93e35535d877.png)

Therefore I beg of thee (: make plugin work with the JS version please (: 

https://github.com/furcan/IconPicker/issues/2 relates too (same problem ```<i>``` replaced with ```<svg>``` elements by Font Awesome )

**Comment by petervanderwalt** [comment]
Refer note at bottom of https://fontawesome.com/how-to-use/on-the-web/setup/getting-started among other documentation

**Comment by furcan** [comment]
Hi,
Firstly thanks for using IconPicker.

This plugin did not design for using FontAwesome JS functionalities.

I noted this request and the next version of IconPicker may have this ability. 

Thanks.
