### ISSUE TITLE
Does this work with the Pro version of Font Awesome ?

### ISSUE THREAD

**Issue by ihmunro** [furcan/IconPicker#5]
Does this work with the Pro version of Font Awesome ?

I have pointed to the new css files etc and I added new Icon detail in the JSON file, but the icon is not shown.

**Comment by furcan** [comment]
Hi @ihmunro 

IconPicker works only with FontAwesome Free and the current version is `v5.11.2`.

If you want to create your own icon set you can create your custom JSON file as well. (Also, you have to add your icon/fonts library into the document to see them.)

An example of JSON is below.

```json
{
  "0": "icon-class-name-1",
  "1": "icon-class-name-2",
  "2": "icon-class-name-3"
}
```

Thanks.
Furkan.

**Comment by ihmunro** [comment]
Many thanks.

The Font Awesome version I have is V 6.

I have added all the css files etc as well as all the svgs etc.

I did try another it pointing to another JSON file, but it did not work.

**Comment by furcan** [comment]
Hi @ihmunro 

This plugin designed and created for FontAwesome Free. So, I did not work with the Pro or V6 version of FontAwesome. So I can not reproduce this request.

You can follow this reply: https://github.com/furcan/IconPicker/issues/5#issuecomment-778782384

Thank you.
